language: cpp

compiler:
  - gcc
  - clang

install:
  - curl -O http://www.cmake.org/files/v3.3/cmake-3.3.0-rc4-Linux-x86_64.tar.gz
  - tar xfz cmake-3.3.0-rc4-Linux-x86_64.tar.gz

script: 
  - ./cmake-3.3.0-rc4-Linux-x86_64/bin/cmake .
  - make -j5
  - ./cmake-3.3.0-rc4-Linux-x86_64/bin/ctest .
  - ./cmake-3.3.0-rc4-Linux-x86_64/bin/cpack .

before_deploy: travis setup releases

deploy:
  provider: releases
  file: traviscitest-1.3.2-Linux.tar.Z
  skip_cleanup: true

os:
  - linux

